### ISSUE TITLE
caligula crashes, unexpected end of file 

### ISSUE THREAD

**Issue by jevidl** [ifd3f/caligula#139]
## Describe the bug
I have attempted to burn to a micro sdcard using caligula. As soon as I give it the confirmation to erase the target disk, it crases with the following: 

`> Is this okay? Yes
An unexpected error occurred: panicked at src/ui/main.rs:39:9:
unexpected end of file`

I can reproduce this choosing either the base disk, or the first slice. I can recreate it using sudo to launch caligula or by having caligula prompt for sudo. I can attach logs from trying to burn the base disk or the first slice. 

## OS/Environment
 - Terminal emulator: alacritty
 - OS: MacOS Sonoma 14.5
 - Version: v0.4.4
 - Distribution channel: darwin-nix

Attachments: 
caligula-46453-1717731989175
[main.log](https://github.com/user-attachments/files/15704380/main.log)
[writer-0.log](https://github.com/user-attachments/files/15704382/writer-0.log)

caligula-45691-1717731787354
[writer-0.log](https://github.com/user-attachments/files/15704688/writer-0.log)
[main.log](https://github.com/user-attachments/files/15704692/main.log)

**Comment by jevidl** [comment]
It is possible this was user error. It did not click that the file was .xz compressed since it seemed like it recognized the compression OK, and could calculate the sha hash against the compressed file. 

The image did successfully burn when I extracted it. 

The file is `Armbian_community_24.8.0-trunk.6_Orangepizero3_bookworm_current_6.6.31_minimal.img.xz`

**Comment by ifd3f** [comment]
Oh, this appears to be an occurence of #124, which I *should* have fixed with v0.4.7. Try that version instead?

**Comment by jevidl** [comment]
Thanks for the quick response! It appears this persists. I wound up doing a fresh nix-darwin install, the upside of which I have caligula v.0.4.7 installed, now. 

I still received the following error: 
```
> Is this okay? Yes
> We don't have permissions on /dev/rdisk4. Escalate using sudo? Yes

An unexpected error occurred: panicked at src/ui/main.rs:51:9:
Explicit failure signaled: Some(UnknownChildProcError("Resource busy (os error 16)"))
```
This is the version: 
```
~ caligula --version
caligula 0.4.7
```

Please see attached files: 
[escalated.log](https://github.com/user-attachments/files/15845620/escalated.log)
[main.log](https://github.com/user-attachments/files/15845622/main.log)
[writer-0.log](https://github.com/user-attachments/files/15845623/writer-0.log)
[writer-1.log](https://github.com/user-attachments/files/15845624/writer-1.log)

**Comment by ifd3f** [comment]
Unfortunately, that would be an occurrence of #105. A workaround is to unmount the filesystem first (I think with some diskctl command? I don't know much about MacOS) but I'll need to go resolve that at some point.

**Comment by jevidl** [comment]
It does look like running `diskutil unmountDisk /dev/disk$ID` does in fact let it write the sd card successfully.
